name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupération du code
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important pour SonarCloud

      # 2. Installation de Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # 3. Build & Test (Maven)
      - name: Build and Test
        run: mvn clean package

      # 4. Analyse SonarCloud
      - name: SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Laissé tel quel
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # Votre secret créé
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=khouloud472_ConsumeSafe \
            -Dsonar.organization=khouloud472 \
            -Dsonar.host.url=https://sonarcloud.io

      # 5. Scan de dépendances (OWASP)
      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'ConsumeSafe'
          path: '.'
          format: 'HTML'
          out: 'reports'

      # 6. Scan de secrets (Gitleaks)
      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 7. Scan Container (Trivy)
      # On construit l'image d'abord pour pouvoir la scanner
      - name: Build Docker Image
        run: docker build -t consumesafetunisia:latest .

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'consumesafetunisia:latest'
          format: 'table'
          exit-code: '0' # On met 0 pour ne pas bloquer le build pour l'instant
          severity: 'CRITICAL,HIGH'
